document.addEventListener('DOMContentLoaded',()=>{
 const {qs,money,cartDetails,totals,toast,safeParse,KEYS,saveOrder,clearCart}=CellStore;
 if(document.body.dataset.page!=='checkout')return;
 const items=cartDetails();if(!items.length){location.replace('cart.html');return}
 const saved=safeParse(localStorage.getItem(KEYS.customer),{}),form=qs('#checkout-form'),proof=qs('#payment-proof'),preview=qs('#proof-preview'),t=totals();
 Object.entries(saved).forEach(([k,v])=>{if(form.elements[k]&&k!=='paymentProof')form.elements[k].value=v});
 const renderSummary=()=>{qs('#checkout-summary').innerHTML=`${items.map(x=>`<div class="summary-product"><img src="${x.product.image}" alt=""><span><b>${x.product.brand} ${x.product.model}</b><small>${x.product.storage} · Qty ${x.qty}</small></span><strong>${money(x.lineTotal)}</strong></div>`).join('')}<div class="summary-lines"><div><span>Subtotal</span><b>${money(t.subtotal)}</b></div><div><span>Shipping</span><b>${money(t.shipping)}</b></div><div class="total"><span>Total</span><b>${money(t.total)}</b></div></div>`;qs('#pay-amount').textContent=money(t.total)};renderSummary();
 const setPreview=(data,name)=>{preview.innerHTML=`<img src="${data}" alt="Payment proof preview"><div><b>Upload ready</b><span>${name}</span></div><button type="button" id="remove-proof" aria-label="Remove proof">×</button>`;preview.classList.add('has-file');proof.dataset.value=data;proof.dataset.filename=name;toast('Payment proof uploaded.')};
 proof.addEventListener('change',()=>{const file=proof.files[0];if(!file)return;const allowed=['image/jpeg','image/png','image/webp'];if(!allowed.includes(file.type)){toast('Please choose a JPG, PNG or WEBP image.','error');proof.value='';return}if(file.size>1500000){toast('Image must be smaller than 1.5MB for localStorage.','error');proof.value='';return}const reader=new FileReader();reader.onload=()=>setPreview(reader.result,file.name);reader.onerror=()=>toast('Could not read that image.','error');reader.readAsDataURL(file)});
 preview.addEventListener('click',e=>{if(!e.target.closest('#remove-proof'))return;proof.value='';delete proof.dataset.value;delete proof.dataset.filename;preview.classList.remove('has-file');preview.innerHTML='<span>Choose a JPG, PNG or WEBP image</span>'});
 const fields=[...form.elements].filter(x=>x.name&&x.type!=='file');fields.forEach(f=>f.addEventListener('input',()=>{const data=Object.fromEntries(new FormData(form));delete data.paymentProof;localStorage.setItem(KEYS.customer,JSON.stringify(data));f.classList.remove('invalid')}));
 form.addEventListener('submit',e=>{e.preventDefault();let valid=true;form.querySelectorAll('[required]').forEach(f=>{const ok=f.type==='file'?Boolean(proof.dataset.value):Boolean(f.value.trim())&&f.checkValidity();f.classList.toggle('invalid',!ok);if(!ok)valid=false});if(!valid){toast('Please complete all required checkout fields.','error');qs('.invalid')?.focus();return}const data=Object.fromEntries(new FormData(form)),num=`ORD-${new Date().getFullYear()}-${Math.floor(10000+Math.random()*90000)}`;const order={orderNumber:num,createdAt:new Date().toISOString(),customer:{name:data.customerName,email:data.email,mobile:data.mobile},shipping:{name:data.shippingName,phone:data.shippingPhone,province:data.province,city:data.city,barangay:data.barangay,street:data.street,postal:data.postal,instructions:data.instructions||''},items:items.map(x=>({id:x.id,qty:x.qty,price:x.product.price,name:`${x.product.brand} ${x.product.model}`})),paymentReference:data.paymentReference,paymentProof:{name:proof.dataset.filename,data:proof.dataset.value},paymentStatus:'Pending Verification',statusIndex:1,totals:t};try{saveOrder(order);clearCart();sessionStorage.setItem('cellstore_celebrate','1');toast('Order placed successfully.');setTimeout(()=>location.href=`order.html?id=${encodeURIComponent(num)}`,500)}catch(err){toast('Could not save order. Try a smaller proof image.','error')}});
});
