document.addEventListener('DOMContentLoaded',()=>{
 if(document.body.dataset.page!=='order')return;
 const {qs,money,loadOrder,loadOrders,updateOrderStatus,toast}=CellStore;
 const statuses=['Order Placed','Payment Verification','Payment Confirmed','Preparing Order','Packed','Shipped','Out for Delivery','Delivered'];
 let id=new URLSearchParams(location.search).get('id')||localStorage.getItem('cellstore_last_order'),order=id?loadOrder(id):null;
 const searchBox=qs('#track-search'),content=qs('#order-content');
 const confetti=()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const layer=qs('.confetti');layer.innerHTML='';for(let i=0;i<45;i++){const s=document.createElement('i');s.style.cssText=`--x:${Math.random()*100}%;--d:${Math.random()*1.6}s;--r:${Math.random()*360}deg;--c:${['#b8f23f','#4c7dff','#ff6b35','#ffd166'][i%4]}`;layer.append(s)}setTimeout(()=>layer.innerHTML='',3500)};
 const render=()=>{if(!order){content.innerHTML=`<div class="track-empty"><span>⌕</span><h1>Track a demo order</h1><p>Enter an order number created in this browser.</p><form id="track-form"><input id="track-id" placeholder="ORD-2026-48291" required><button class="btn btn-accent">Track order</button></form>${loadOrders().length?`<small>Recent: ${loadOrders().slice(0,3).map(o=>o.orderNumber).join(', ')}</small>`:''}</div>`;qs('#track-form').addEventListener('submit',e=>{e.preventDefault();const found=loadOrder(qs('#track-id').value.trim());if(!found){toast('Order not found in this browser.','error');return}order=found;history.replaceState({},'',`?id=${order.orderNumber}`);render()});return}
 const address=`${order.shipping.street}, Brgy. ${order.shipping.barangay}, ${order.shipping.city}, ${order.shipping.province} ${order.shipping.postal}`;
 content.innerHTML=`<section class="success-hero ${order.statusIndex===7?'delivered':''}"><div class="success-mark">✓</div><p class="eyebrow">${order.statusIndex===7?'Delivery complete':'Order confirmation'}</p><h1>${order.statusIndex===7?'Delivered successfully':'Order received!'}</h1><p>${order.statusIndex===7?'Your demo order reached its final status.':'Thank you for your order. Payment verification is pending.'}</p><div class="order-facts"><div><span>Order</span><b>${order.orderNumber}</b></div><div><span>Payment</span><b>${order.paymentStatus}</b></div><div><span>Total</span><b>${money(order.totals.total)}</b></div></div></section><div class="order-layout"><section class="tracking-card"><div class="section-title"><div><p class="eyebrow">Demo order tracking</p><h2>${statuses[order.statusIndex]}</h2></div><span class="demo-badge">No backend</span></div><div class="motion-stage ${order.statusIndex===3?'preparing':''} ${order.statusIndex>=5&&order.statusIndex<7?'shipping':''} ${order.statusIndex===7?'done':''}"><div class="package">▣</div><div class="truck">▰</div><span>${order.statusIndex===3?'Preparing your phone':order.statusIndex>=5&&order.statusIndex<7?'Demo delivery in motion':order.statusIndex===7?'Delivered':'Status simulator ready'}</span></div><ol class="status-list">${statuses.map((s,i)=>`<li class="${i<order.statusIndex?'complete':i===order.statusIndex?'current':''}"><span>${i<order.statusIndex?'✓':i===order.statusIndex?'●':'○'}</span><b>${s}</b></li>`).join('')}</ol><button id="next-status" class="btn btn-accent full" ${order.statusIndex===7?'disabled':''}>${order.statusIndex===7?'Delivered':'Simulate next status'}</button><p class="demo-note">This control only updates localStorage for demonstration. Real order updates require a secure backend.</p></section><aside class="order-card"><h2>Delivery details</h2><p><b>${order.shipping.name}</b><br>${address}<br>${order.shipping.phone}</p><h3>Items</h3>${order.items.map(x=>`<div><span>${x.name} × ${x.qty}</span><b>${money(x.price*x.qty)}</b></div>`).join('')}<div class="total"><span>Total</span><b>${money(order.totals.total)}</b></div></aside></div>`;
 qs('#next-status')?.addEventListener('click',()=>{if(order.statusIndex>=7)return;order=updateOrderStatus(order.orderNumber,order.statusIndex+1);if(order.statusIndex===2)order.paymentStatus='Pending Verification';render();toast(`Status updated: ${statuses[order.statusIndex]}.`);if(order.statusIndex===7)confetti()});if(sessionStorage.getItem('cellstore_celebrate')){sessionStorage.removeItem('cellstore_celebrate');confetti()}};render();
});
