window.CellStore = window.CellStore || {};
window.CellStore.products = [
 {id:'redmi-a5',brand:'Redmi',model:'A5',category:'Android',storage:'64GB',color:'Ocean Blue',price:1999,originalPrice:2499,stock:18,newest:false,featured:true,image:'assets/images/phone-light.jpg',condition:'Brand New',description:'Everyday performance, a large display, and reliable battery life at an accessible price.',specs:['6.7-inch display','5000mAh battery','Dual SIM','4G LTE']},
 {id:'redmi-note-14',brand:'Redmi',model:'Note 14',category:'Android',storage:'128GB',color:'Midnight Black',price:9999,originalPrice:10999,stock:12,newest:true,featured:true,image:'assets/images/phone-dark.jpg',condition:'Brand New',description:'A balanced daily driver with a vivid screen, sharp camera and generous storage.',specs:['6.67-inch AMOLED','108MP camera','5500mAh battery','Fast charging']},
 {id:'samsung-a06',brand:'Samsung',model:'Galaxy A06',category:'Android',storage:'128GB',color:'Black',price:5999,originalPrice:6499,stock:9,newest:false,featured:false,image:'assets/images/phone-dark.jpg',condition:'Brand New',description:'Simple, dependable and built for everyday messaging, streaming and photos.',specs:['6.7-inch display','50MP camera','5000mAh battery','Knox Vault']},
 {id:'samsung-a16',brand:'Samsung',model:'Galaxy A16',category:'Android',storage:'128GB',color:'Light Green',price:7999,originalPrice:8999,stock:14,newest:true,featured:true,image:'assets/images/phone-light.jpg',condition:'Brand New',description:'A crisp AMOLED experience with dependable security and all-day power.',specs:['6.7-inch AMOLED','50MP triple camera','5000mAh battery','6 OS upgrades']},
 {id:'realme-c75',brand:'Realme',model:'C75',category:'Android',storage:'128GB',color:'Lightning Gold',price:8999,originalPrice:9999,stock:7,newest:true,featured:false,image:'assets/images/phone-light.jpg',condition:'Brand New',description:'Tough construction and long battery life for work, travel and entertainment.',specs:['ArmorShell protection','6000mAh battery','45W charging','IP69 rating']},
 {id:'oppo-a5',brand:'Oppo',model:'A5',category:'Android',storage:'128GB',color:'Aurora Green',price:7999,originalPrice:null,stock:6,newest:true,featured:false,image:'assets/images/phone-light.jpg',condition:'Brand New',description:'Smooth everyday performance with a vibrant design and useful portrait camera.',specs:['120Hz display','50MP camera','5100mAh battery','Dual SIM']},
 {id:'vivo-y19s',brand:'Vivo',model:'Y19s',category:'Android',storage:'128GB',color:'Pearl Silver',price:6999,originalPrice:7499,stock:11,newest:false,featured:false,image:'assets/images/phone-light.jpg',condition:'Brand New',description:'A slim and practical phone for daily productivity, social apps and entertainment.',specs:['6.68-inch display','50MP camera','5500mAh battery','Stereo speakers']},
 {id:'xiaomi-note-14-pro',brand:'Xiaomi',model:'Redmi Note 14 Pro',category:'Android',storage:'256GB',color:'Graphite Gray',price:14999,originalPrice:16999,stock:5,newest:true,featured:true,image:'assets/images/phone-dark.jpg',condition:'Brand New',description:'Pro-level imaging and performance in a polished, durable package.',specs:['200MP camera','Curved AMOLED','Turbo charging','IP68 rating']},
 {id:'iphone-11',brand:'Apple',model:'iPhone 11',category:'iPhone',storage:'64GB',color:'Black',price:15999,originalPrice:17999,stock:4,newest:false,featured:false,image:'assets/images/phone-dark.jpg',condition:'Excellent Renewed',description:'A proven iPhone experience with reliable cameras and smooth everyday performance.',specs:['6.1-inch Liquid Retina','Dual 12MP camera','Face ID','A13 Bionic']},
 {id:'iphone-12',brand:'Apple',model:'iPhone 12',category:'iPhone',storage:'128GB',color:'Blue',price:18999,originalPrice:20999,stock:8,newest:false,featured:true,image:'assets/images/phone-light.jpg',condition:'Excellent Renewed',description:'A bright OLED display, 5G and a compact flat-edge design.',specs:['6.1-inch OLED','5G capable','MagSafe','A14 Bionic']},
 {id:'iphone-13',brand:'Apple',model:'iPhone 13',category:'iPhone',storage:'128GB',color:'Midnight',price:22999,originalPrice:25999,stock:10,newest:false,featured:true,image:'assets/images/phone-dark.jpg',condition:'Excellent Renewed',description:'Excellent battery life and camera performance in a refined design.',specs:['6.1-inch OLED','Cinematic mode','MagSafe','A15 Bionic']},
 {id:'iphone-14',brand:'Apple',model:'iPhone 14',category:'iPhone',storage:'128GB',color:'Starlight',price:27999,originalPrice:30999,stock:5,newest:false,featured:false,image:'assets/images/phone-light.jpg',condition:'Brand New',description:'A powerful dual-camera system with dependable all-day performance.',specs:['6.1-inch OLED','Crash Detection','Photonic Engine','A15 Bionic']},
 {id:'iphone-15',brand:'Apple',model:'iPhone 15',category:'iPhone',storage:'128GB',color:'Blue',price:32999,originalPrice:36999,stock:9,newest:true,featured:true,image:'assets/images/phone-light.jpg',condition:'Brand New',description:'Dynamic Island, USB-C and a 48MP camera in a color-infused glass design.',specs:['6.1-inch OLED','48MP camera','USB-C','A16 Bionic']},
 {id:'iphone-16',brand:'Apple',model:'iPhone 16',category:'iPhone',storage:'128GB',color:'Ultramarine',price:39999,originalPrice:42999,stock:3,newest:true,featured:true,image:'assets/images/phone-dark.jpg',condition:'Brand New',description:'Latest-generation performance with Camera Control and thoughtful everyday intelligence.',specs:['6.1-inch OLED','Camera Control','Action button','A18 chip']}
];
